FROM i386/alpine:3.23 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/go-mcp-server"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/go-mcp-server /usr/bin/go-mcp-server
